name: Meta Build Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch or ref to build from"
        required: true
        default: "main"
      buildConfig:
        description: "JSON describing how/what to build"
        required: false

jobs:
  meta-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Parse buildConfig if provided
        id: parse_config
        run: |
          if [ -n "${{ github.event.inputs.buildConfig }}" ]; then
            echo "${{ github.event.inputs.buildConfig }}" > buildConfig.json
            echo "Build config contents:"
            cat buildConfig.json
          else
            echo "No buildConfig provided. Using default."
          fi

      - name: Extract Dockerfile path
        if: ${{ always() }}
        id: get_dockerfile
        run: |
          # If buildConfig.json exists, read the dockerfile field with 'jq'.
          # Otherwise, set a default path or skip.
          if [ -f buildConfig.json ]; then
            DOCKERFILE_PATH=$(jq -r '.dockerfile' buildConfig.json)
            if [ "$DOCKERFILE_PATH" = "null" ]; then
              echo "Dockerfile path not found in buildConfig.json. Exiting."
              exit 1
            fi
          else
            echo "No buildConfig.json found. Exiting or set your default path here."
            exit 1
          fi
          echo "::set-output name=path::$DOCKERFILE_PATH"

      - name: Build Docker image
        run: |
          DOCKERFILE="${{ steps.get_dockerfile.outputs.path }}"
          echo "Building Docker image from $DOCKERFILE"
          docker build -t myorg/myapp:latest -f "$DOCKERFILE" .
